apiVersion: v1
kind: ConfigMap
metadata:
  name: faf-user-service
  labels:
    app: faf-user-service
data:
  # Only for testing environments
  FAF_ENVIRONMENT: "K8S"
  REAL_IP_HEADER: "Cf-Connecting-Ip"
  PASSWORD_RESET_URL: "https://www.{{.Values.baseDomain}}/account/password/reset"
  REGISTER_ACCOUNT_URL: "https://www.{{.Values.baseDomain}}/account/register"
  FAILED_LOGIN_ACCOUNT_THRESHOLD: "5"
  FAILED_LOGIN_ATTEMPT_THRESHOLD: "10"
  FAILED_LOGIN_THROTTLING_MINUTES: "5"
  FAILED_LOGIN_DAYS_TO_CHECK: "1"
  HYDRA_ISSUER: "https://hydra.{{.Values.baseDomain}}/"
  HYDRA_JWKS_URL: "https://hydra.{{.Values.baseDomain}}/.well-known/jwks.json"
  HYDRA_BASE_ADMIN_URL: "http://ory-hydra:4445"
  DB_URL: "jdbc:mariadb://faf-db:6900/faf_lobby?ssl=false"
  DB_USERNAME: faf-user-service
