apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: faf-user-service
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`user.{{.Values.baseDomain}}`)
      kind: Rule
      services:
        - name: faf-user-service
          port: 8080
