apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: faf-user-service
  namespace: faf-ops
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-ops
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/faf-user-service"
  managedSecretReference:
    secretName: faf-user-service
    secretNamespace: faf-apps

