apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  replicas: 3
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: containous/whoami
        name: whoamicontainer
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
  internalTrafficPolicy: Local

---
apiVersion: v1
kind: Service
metadata:
  name: whoami-sticky
  labels:
    app: whoami
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  selector:
    app: whoami
  ports:
  - port: 80
    targetPort: 80
  internalTrafficPolicy: Local
