apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: faf-unitdb
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unitdb.{{.Values.baseDomain}}`)
      kind: Rule
      services:
        - name: faf-unitdb
          port: 80
