environment: prod
infisicalSlug: prod
baseDomain: faforever.com
zfs:
  nodeId: fafprod3
  poolName: tank/faf
  datasetPrefix: k8s-
  # On NixOS, we need to declare the ZFS binary path explicitly
  bin: /run/current-system/sw/bin/zfs
