apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: faf-icebreaker
  namespace: faf-ops
spec:
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: faf-ops
      secretsScope:
        envSlug: {{.Values.infisicalSlug}}
        secretsPath: "/faf-icebreaker"
  managedSecretReference:
    secretName: faf-icebreaker
    secretNamespace: faf-apps

